//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Entity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPDbEntities : DbContext
    {
        public ERPDbEntities()
            : base("name=ERPDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_MstAccessMainMenu> tbl_MstAccessMainMenu { get; set; }
        public virtual DbSet<tbl_MstAccessPages> tbl_MstAccessPages { get; set; }
        public virtual DbSet<tbl_MstAccessSubMenu> tbl_MstAccessSubMenu { get; set; }
        public virtual DbSet<tbl_MstCategory> tbl_MstCategory { get; set; }
        public virtual DbSet<tbl_MstEmails> tbl_MstEmails { get; set; }
        public virtual DbSet<tbl_MstMerchants> tbl_MstMerchants { get; set; }
        public virtual DbSet<tbl_MstMerchantsRoleXref> tbl_MstMerchantsRoleXref { get; set; }
        public virtual DbSet<tbl_MstRoles> tbl_MstRoles { get; set; }
        public virtual DbSet<tbl_MstSubCategory> tbl_MstSubCategory { get; set; }
    }
}
