//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mst_AdvertisePlans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Mst_AdvertisePlans()
        {
            this.tbl_AdvertisePlansXref = new HashSet<tbl_AdvertisePlansXref>();
        }
    
        public int pkId { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public Nullable<int> ListingLimit { get; set; }
        public Nullable<decimal> PlanValue { get; set; }
        public Nullable<int> PlanLimitInDays { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifedBy { get; set; }
        public Nullable<System.DateTime> ModifedDate { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AdvertisePlansXref> tbl_AdvertisePlansXref { get; set; }
    }
}
