//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RMASHEET
    {
        public int Id { get; set; }
        public string CP_NO { get; set; }
        public string JOB_NO { get; set; }
        public string PARTY { get; set; }
        public string UID { get; set; }
        public string GRADE { get; set; }
        public string BILLET_SIZE { get; set; }
        public string APPROX_TON_PENDING { get; set; }
        public string S_PER { get; set; }
        public string P_PER { get; set; }
        public string LEN_FINISH_MAT { get; set; }
        public string B { get; set; }
        public string ED_DATE { get; set; }
        public string TDC_REF { get; set; }
        public string INT_PRODUCT_STD_SERIES_NO { get; set; }
        public string BILLET_LENGTH { get; set; }
        public string NO_OF_PCS { get; set; }
        public string APPROX_QTY_BILLET { get; set; }
        public string SIZE_FOR_ROLLING { get; set; }
        public string SHAPE { get; set; }
        public string FINISHED_SIZE { get; set; }
        public string RMA_NO { get; set; }
        public string HEAT_NO { get; set; }
        public string PCS { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public string RMA_DT { get; set; }
        public string REPLAN { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
