//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mst_Advertise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Mst_Advertise()
        {
            this.tbl_Mst_AdvertiseImageXref = new HashSet<tbl_Mst_AdvertiseImageXref>();
        }
    
        public int Id { get; set; }
        public Nullable<int> fkSubCategory { get; set; }
        public string Add_Id { get; set; }
        public string Add_Title { get; set; }
        public string Add_Description { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Selling_Price { get; set; }
        public Nullable<int> IsMobileView { get; set; }
        public string Geo_Lat { get; set; }
        public string Geo_Long { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Neighbourhood { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> Ad_Views { get; set; }
    
        public virtual tbl_MstSubCategory tbl_MstSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Mst_AdvertiseImageXref> tbl_Mst_AdvertiseImageXref { get; set; }
    }
}
