//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mst_AdvertiseImageXref
    {
        public int Id { get; set; }
        public Nullable<int> fkAdd_Id { get; set; }
        public string ImagePath { get; set; }
        public string ImagePath_Thumb { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifedDate { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual tbl_Mst_Advertise tbl_Mst_Advertise { get; set; }
    }
}
